name: "research"

on:
  workflow_dispatch:

jobs:
  build-and-test-ubuntu:
    name: Build And Test Ubuntu
    runs-on: ubuntu-latest
    env:
      CI_BUILD: 1
      IMAGE: ubuntu
      IMAGE_TAG: latest
    steps:
      - uses: actions/checkout@main

      - name: Update packages
        run: sudo -E bash .github/update-packages.sh

      - name: Install dependencies
        run: |
          sudo -E bash .github/install.sh
          sudo -E bash .github/install-post.sh

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: c-cpp
          queries: security-extended,security-and-quality

      - name: Build and run tests
        run: bash .github/build.sh

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:c-cpp"
